name: CD

on:
  push:
    branches: [stage]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@stage
      - name: deploy files via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          source: "index.html"
          target: "moon.scs.ryerson.ca/home/avm/courses/cps847/${{ secrets.DEPLOY_USERNAME }}"
